apiVersion: v2
name: fulcio
description: |
  Fulcio is a free code signing Certificate Authority, built to make short-lived certificates available to anyone.

type: application

version: 2.3.17
appVersion: 1.4.4

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: ctlog
    version: 0.2.51
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: fulcio
      image: gcr.io/projectsigstore/fulcio@sha256:d4e075bfaf0539a5220f3a76b80454261ecda443248fce283fd185d27e9910d4
    - name: createcerts
      image: ghcr.io/sigstore/scaffolding/createcerts:v0.6.16@sha256:ad6a4721b7c8f529ae703129a076443c3f47cc1101421323db805620e782192a
